### ISSUE TITLE
server value modifier

### ISSUE THREAD

**Issue by MOMO-Devil** [CathieNova/SPT-Haven-Industries-Chloe#2]
it gave some error when i start it with the mod ServerValueModifier with the Remove secure container filter button

**Comment by MOMO-Devil** [comment]
TypeError: Cannot read properties of undefined (reading 'Filter')
TypeError: Cannot read properties of undefined (reading 'Filter')
    at SampleTrader.allowIntoCaseByParent (F:\naja\user\mods\Haven Industries - Chloe\src\mod.ts:245:48)
    at SampleTrader.allowIntoContainers (F:\naja\user\mods\Haven Industries - Chloe\src\mod.ts:236:22)
    at SampleTrader.createCase (F:\naja\user\mods\Haven Industries - Chloe\src\mod.ts:223:14)
    at SampleTrader.postDBLoad (F:\naja\user\mods\Haven Industries - Chloe\src\mod.ts:89:14)
    at PostDBModLoader.executeModsAsync (C:\snapshot\src\loaders\PostDBModLoader.ts:63:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\src\utils\App.ts:51:26)
TypeError: Cannot read properties of undefined (reading 'Filter')
TypeError: Cannot read properties of undefined (reading 'Filter')
    at SampleTrader.allowIntoCaseByParent (F:\naja\user\mods\Haven Industries - Chloe\src\mod.ts:245:48)
    at SampleTrader.allowIntoContainers (F:\naja\user\mods\Haven Industries - Chloe\src\mod.ts:236:22)
    at SampleTrader.createCase (F:\naja\user\mods\Haven Industries - Chloe\src\mod.ts:223:14)
    at SampleTrader.postDBLoad (F:\naja\user\mods\Haven Industries - Chloe\src\mod.ts:89:14)
    at PostDBModLoader.executeModsAsync (C:\snapshot\src\loaders\PostDBModLoader.ts:63:45)
    at PostDBModLoader.onLoad (C:\snapshot\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\src\utils\App.ts:51:26)

**Comment by CathieNova** [comment]
This is an easy fix, i'll update the mod later but if you want the fix now you can:

[Drop this in the config folder](https://github.com/user-attachments/files/17918895/mod_config.json)

Then open the mod.ts file and find "allowIntoCaseByParent" and replace the text with this:
`allowIntoCaseByParent(customItemID, include, currentItem, caseParent): void {
        if (modConfig.enableSecureCase) {
            if (include === "include"){
                if (currentItem._parent === caseParent && currentItem._id !== "5c0a794586f77461c458f892"){
                    for (const grid of currentItem._props.Grids) {
                        if (grid._props.filters[0].Filter === undefined){
                            grid._props.filters[0].Filter = [customItemID];
                        } else {
                            grid._props.filters[0].Filter.push(customItemID)
                        }
                    }
                }
            }
        }
    }`

Then you should be able to use ServerValueModifier the Remove secure container filter button.

**Comment by MOMO-Devil** [comment]
damn im to stupid
